<section id="main-content">
	<div class="container-920 padded clearfix">

		<section class="column-265">
			<h2>Recent Additions</h2>
			<div id="equipment-cycle">
				<a class="box-link" href="#">
					<section>
						<img class="border" alt="Toyota Skid Steer 45DK8" src="/images/equipment/modern-house-in-tempe-arizona-1.jpg">
						<h3 class="equipment-heading">Modern Home</h3>
					</section>
				</a>
				<a class="box-link" href="#">
					<section>
						<img class="border" alt="Machine Builder" src="/images/equipment/mac2.jpeg">
						<h3 class="equipment-heading">Machine Builder</h3>
					</section>
				</a>
			</div>
			<div class="cycle-navigation equipment-cycle">
				<a class="prev ir">Previous</a><div class="cycle-nav"></div><a class="next ir">Next</a>
			</div>
		</section>

		<section class="column-265">
			<h2>PG Nish Engineering &amp; Services</h2>
			<div id="news-cycle">
				<section>
					<h3>Constructability Reviews</h3>
					<p>PG NISH Engineering is capable of reviewing construction processes from start to finish during the pre-construction phrase. We will identify obstacles before a project is actually built to reduce or prevent error, delays and cost overruns. </p>
					<a class="block-button" href="#">Read more</a>	
				</section>
				
				<section>
					<h3>Construction Planning</h3>
					<p>We can advice on the choice of technology, the definition of work tasks, the estimation of the required resources and durations for individual tasks, and the identification of any interactions among the different work tasks.</p>
					
					<a class="block-button" href="#">Read more</a>
				</section>

				<!--section>
					<h3>Construction Staging & Traffic Management Solutions</h3>
					<p>We have experts to analyze the construction staging and develop appropriate traffic management plans so that there is no delay to construction activities and no cost overrun.</p>	
					<a class="block-button" href="#">Read more</a>
				</section-->
			</div>
			<div class="cycle-navigation news-cycle">
				<a class="prev ir">Previous</a><div class="cycle-nav"></div><a class="next ir">Next</a>
			</div>
		</section>

		<section class="column-265">
			<h2>Project List</h2>
			<ul id="category-cycle">
				<a class="up ir">Up</a>
				<div class="list">
					<?php foreach ($accounts as $account) : ?>
						<div>
							<li><a href="<?php echo $this->escapeHtml($account->id); ?>"><?php echo $this->escapeHtml($account->name) ?></a></li>
						</div>
					<?php endforeach; ?>
				</div>
				<a class="down ir">Down</a>
			</ul>
		</section>
	</div>
</section>

<section id="ad-content">
	<div class="container-920 padded clearfix">
		<ul id="ul_main" class="no-bullets"> 
			<li class="web_design">
				<a href="web_design_perth.php">
					<hgroup>
					</hgroup>
				</a>
			</li>

			<li class="cms">
				<a href="cms_integration_perth.php">
					<hgroup>
					</hgroup>
				</a>
			</li>

			<li class="magento">
				<a href="magento_development_perth.php">
					<hgroup>
					</hgroup>
				</a>
			</li>

			<li class="linux">
				<a href="linux_administration_services_perth.php">
					<hgroup>
					</hgroup>
				</a>
			</li>
		</ul>
	</div>
</section>

<section id="main-content">
	<div class="container-920 padded clearfix">
		<section class="column-700">
			<h2>Latest News &amp; Projects</h2>
			<div id="news-cycle">
				<section>
					<h3>National Construction Excellence Awards, <span>2012</span></h3>
					<p>Maga Engineering was the recipient of 8 Awards at the 2012 National Construction Excellence Awards ceremony organized by Institute for Construction Training and Development (ICTAD). This takes Magas tally of National Construction Awards to a record 57.</p>
					<a class="block-button" href="#">Read more</a>	
				</section>
			</div>
		</section>
	</div>
</section>

<section id="social">
	<div class="container-920 padded clearfix">
		<!--ul id="ul_main" class="no-bullets"> 
			<li class="web_design">
				<a href="web_design_perth.php">
					<hgroup>
						<h2>LABOUR HIRE</h2>
						<h3></h3>
					</hgroup>
				</a>
			</li>

			<li class="cms">
				<a href="cms_integration_perth.php">
					<hgroup>
						<h2>HOME DESIGN</h2>
						<h3></h3>
					</hgroup>
				</a>
			</li>

			<li class="magento">
				<a href="magento_development_perth.php">
					<hgroup>
						<h2>ALUMINUM WORK</h2>
						<h3></h3>
					</hgroup>
				</a>
			</li>

			<li class="linux">
				<a href="linux_administration_services_perth.php">
					<hgroup>
						<h2>TOURISAM</h2>
						<h3></h3>
					</hgroup>
				</a>
			</li>
		</ul-->
	</div>
</section>

